- app/Http/Controllers/DashboardController.php
- app/Http/Controllers/RecordController.php
- app/Http/Controllers/ServerController.php
- app/Http/Controllers/SettingsController.php
- app/Http/Controllers/ToolsController.php
- app/Http/Controllers/ZoneController.php
- config/app.php
- database/factories/ModelFactory.php
- database/migrations/2014_10_12_000000_create_users_table.php
- database/migrations/2014_10_12_100000_create_password_resets_table.php
- database/migrations/2016_08_05_100108_create_zones_table.php
- database/migrations/2016_08_05_101710_create_records_table.php
- database/migrations/2016_08_05_104147_create_servers_table.php
- database/seeds/ZonesTableSeeder.php
@pacoorozco requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/pacoorozco/probind/
> Scrutinizer Auto-Fixes

- app/Console/Commands/ProBINDPushZones.php
- app/Console/Kernel.php
- app/Http/Controllers/ServerController.php
- app/Http/Controllers/ZoneController.php
- app/Http/Requests/SettingsUpdateRequest.php
- app/Server.php
- database/migrations/2016_08_05_104147_create_servers_table.php
- database/seeds/SettingsTableSeeder.php
- public/css/probind.css
- resources/lang/en/settings/model.php
- resources/lang/en/settings/title.php
- resources/views/server/_form.blade.php
- resources/views/settings/_form.blade.php
- resources/views/settings/_ssh_settings.blade.php
- resources/views/settings/_zone_settings.blade.php
- resources/views/zone/_form_master.blade.php
Create SSH Global Settings page in order to configure how ProBIND access to DNS servers.
> Create ssh settings

- CHANGELOG.md
- app/Console/Commands/ProBINDImportZone.php
- app/FileDNSParser.php
- app/Http/Controllers/SearchController.php
- app/Http/Controllers/ZoneController.php
- app/Http/Requests/RecordCreateRequest.php
- app/Record.php
- app/Zone.php
- database/factories/ModelFactory.php
- database/migrations/2016_08_05_100108_create_zones_table.php
- database/seeds/ZonesTableSeeder.php
- resources/lang/en/record/model.php
- resources/views/record/_form.blade.php
- tests/ProBINDImportZoneTest.php
- tests/ZoneUnitTest.php
Add support for **reverse zones** (format: `.in-addr.arpa.`).
> Add reverse zones

- app/User.php
Password was assigned not hashed into the database.
> Hashing the password when it's assigned

- app/User.php
Reverts pacoorozco/probind#29
This change affects to table seeding, so we need to change before. Merge must be done on `develop` branch.
> Revert "Hashing the password when it's assigned"

- README.md
Signed-off-by: Paco Orozco <paco@pacoorozco.info>
> Add Docker documentation

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
update issue templates to make easier submission
> doc: update issue templates

- docker/web/Dockerfile
Resolve error "adduser: group 'www-data' in use" in the web service
> Resolve error "adduser: group 'www-data' in use"

- CHANGELOG.md
- app/Http/Controllers/RecordController.php
- app/Http/Requests/RecordCreateRequest.php
- tests/Feature/RecordHttpTest.php
/kind bug
resolves #66
No
**Does this pull request add new dependencies?**  
No
> Fix TTL validation error when creating a new record

- README.md
- app/Console/Commands/ProBINDImportZone.php
- app/Zone.php
- composer.json
- composer.lock
- docker/app/Dockerfile
- tests/Feature/ProBINDImportZoneTest.php
- tests/Unit/ZoneUnitTest.php
- tests/testData/forward_zone.txt
- tests/testData/reverse_zone.txt
- tests/testData/sample_zone.txt
Instead of using our own DNS file parser, we switch to [Badcow/DNS](https://github.com/Badcow/DNS/) library.
Resolves #67
> Change DNS file parser

- .symfony.insight.yaml
- README.md
/kind bug
Remove Symphoy Insights
> Remove symfony insights configuration and badge

- CHANGELOG.md
- README.md
- docker-compose.yml
- docker/app/Dockerfile
- docker/web/Dockerfile
- docker/web/nginx.conf
- docker/web/sites/default.conf
/kind bug
resolves #80 
Yes, documentation has been updated to install dependencies inside docker
> Fix bug issue #80

- CHANGELOG.md
- README.md
- docker-compose.yml
- docker/app/Dockerfile
- docker/web/Dockerfile
/kind bug
resolves #82 
Yes, the documentation has been updated, the new exported variable is `DOCKER_PROBIND_UID`.
> Change exported variable to create user on docker

- README.md
Add video presentation
[![probind: short presentation](https://img.youtube.com/vi/_iaZ3UG3zug/0.jpg)](http://www.youtube.com/watch?v=_iaZ3UG3zug)
> Add video presentation to README

- CHANGELOG.md
- composer.json
- composer.lock
/kind bug
closes #105 , closes #102 
No
**Does this pull request add new dependencies?**  
No, it just update them
> Upgrade dependencies

- app/Record.php
- composer.lock
- resources/views/templates/config_master.blade.php
- resources/views/templates/config_slave.blade.php
- resources/views/templates/zone.blade.php
- tests/Unit/RecordUnitTest.php
> Fix issue 112

- resources/views/templates/zone.blade.php
> Fix missing TTL in zone creation

- resources/views/dashboard/index.blade.php
> Fix broken link to 'Manage users'

- resources/views/record/_table.blade.php
- resources/views/search/_table.blade.php
- resources/views/server/_table.blade.php
- resources/views/user/_table.blade.php
- resources/views/zone/_table.blade.php
> Make DataTables responsive

- app/Zone.php
- resources/views/record/_form.blade.php
> Set default record types depending the zone type

- app/Console/Commands/ProBINDImportZone.php
- app/Http/Controllers/ToolsController.php
- app/Http/Requests/ImportZoneRequest.php
- resources/views/tools/import_zone.blade.php
- resources/views/tools/import_zone_result.blade.php
- routes/web.php
- tests/Feature/ProBINDImportZoneTest.php
> Fix import zone tool

- composer.lock
- docker/app/Dockerfile
Signed-off-by: pacoorozco <paco@pacoorozco.info>
/kind bug
resolves vulnerability in composer <2.0.19
> Update composer version

- app/Http/Controllers/ServerController.php
- app/Http/Requests/ServerCreateRequest.php
- app/Http/Requests/ServerUpdateRequest.php
- app/Presenters/ServerPresenter.php
- database/factories/ServerFactory.php
- resources/views/server/_details.blade.php
- resources/views/server/_form.blade.php
- tests/Feature/Http/Controllers/ServerControllerTest.php
Signed-off-by: pacoorozco <paco@pacoorozco.info>
/kind bug
resolves #153
> Fix issue 153: Can not save server

- CHANGELOG.md
- docker/app/Dockerfile
It allows remote debugging using the `app` docker.
```
$ docker-compose exec app composer test-coverage
```
> Enable Xdebug extension in the app docker

- app/Http/Controllers/SettingsController.php
- app/Http/Controllers/ZoneController.php
- app/Http/Requests/SettingsUpdateRequest.php
- app/Http/Requests/ZoneCreateRequest.php
- app/Http/Requests/ZoneRequest.php
- app/Http/Requests/ZoneUpdateRequest.php
- app/Models/Zone.php
- app/Presenters/ZonePresenter.php
- database/factories/ZoneFactory.php
- resources/views/zone/_form_master.blade.php
- resources/views/zone/_form_slave.blade.php
- resources/views/zone/_table.blade.php
- routes/web.php
- tests/Feature/Http/Controllers/ResourceRecordControllerTest.php
- tests/Feature/Http/Controllers/ServerControllerTest.php
- tests/Feature/Http/Controllers/SettingsControllerTest.php
- tests/Feature/Http/Controllers/UserControllerTest.php
- tests/Feature/Http/Controllers/ZoneControllerTest.php
Add tests to increase the code coverage
> Increase code coverage

- app/Presenters/ServerPresenter.php
- app/Services/Formatters/BINDFormatter.php
- resources/views/templates/zone.blade.php
- tests/Feature/Services/Formatters/BINDFormatterTest.php
Add test to the zone file formatter
> Add test to zone formatter

- database/factories/ResourceRecordFactory.php
- tests/Feature/Services/Formatters/BINDFormatterTest.php
> Add test case for reverse zones in BINDFormatter class

- app/Models/Server.php
- app/Services/Formatters/BINDFormatter.php
- tests/Feature/Services/Formatters/BINDFormatterTest.php
- tests/testData/bind-templates/custom-server-template.blade.php
- tests/testData/bind-templates/custom-zone-template.blade.php
> Add test case for configuration files in BINDFormatter class

- .github/workflows/gh-pages.yml
- .gitignore
> Add GitHub pages deployment usin hugo

- .github/workflows/gh-pages.yml
- .gitignore
> Fix GitHub action to deploy documentation [skip-ci]

- docs/static/CNAME
> Adds CNAME configuration

- .github/workflows/gh-pages.yml
> Restrict GitHub Pages action triggering

- README.md
- docs/content/_index.md
- docs/content/usage/getting-started.md
> First documentation release

- .github/workflows/gh-pages.yml
- docs/archetypes/default.md
- docs/content/_index.md
- docs/content/usage/getting-started.md
> Remove draft status in docs

- .github/workflows/run-tests.yml
> Add filter to avoid running tests in doc changes

- docs/content/usage/getting-started.md
> Add toc to getting-started

- app/Exceptions/Handler.php
- app/Http/Controllers/Auth/ResetPasswordController.php
- app/Http/Controllers/ImportZoneController.php
- app/Http/Controllers/ResourceRecordController.php
- app/Http/Middleware/Authenticate.php
- app/Http/Requests/UserUpdateRequest.php
- app/Presenters/ServerPresenter.php
- app/Presenters/ZonePresenter.php
> Fixes scrutinizer messages

- .github/workflows/phpstan.yml
We are going to remove Scrutinizer, first we are adding a new workflow to run static code analysis using [PHPstan](https://phpstan.org/) (powered with [larastan](https://github.com/nunomaduro/larastan))
> Add a workflow to run phpstan

- docs/content/_index.md
> Removes Scrutinizer badges from doc

- .github/workflows/run-tests.yml
> Upload code coverage reports to Codecov

- README.md
- docs/content/_index.md
> Add Codecov badges

- README.md
- docs/content/_index.md
> Fix readme

- app/Http/Controllers/InstallController.php
- resources/views/install/database.blade.php
- resources/views/install/welcome.blade.php
Debug Error's on Installation pages
use **url name** instead of **ControllerName**
> replaced name of url's with ControllerName

- app/Http/Middleware/AjaxRequestOnly.php
/kind bug
Bug on AjaxRequestOnly middleware
> Fix bug AjaxRequestOnly middleware

- AUTHORS
- README.md
- app/Console/Commands/ProBINDPushZones.php
- composer.json
- config/app.php
- docker-compose.yml
- docs/content/_index.md
- docs/content/guide/getting-started.md
- docs/content/guide/introduction.md
- resources/bind-templates/README.md
- resources/views/layouts/admin.blade.php
- resources/views/layouts/installer.blade.php
- resources/views/layouts/login.blade.php
- resources/views/partials/header.blade.php
- Remove PHPmyAdmin container
- Rename ProBIND v3 to ProBIND3
> Rename app to ProBIND3
